AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  XGBoost Lambda
  
  Provided by MLPacks.com

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: lambda
  XGBoostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      MemorySize: 256
      Layers:
        - PASTE HERE YOUR LAYER ARN
      Events:
        XGBoost:
          Type: Api
          Properties:
            Path: /xgboost
            Method: get
            RestApiId: !Ref ApiGateway

Outputs:
  XGBoostApi:
    Description: "API URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/lambda/xgboost/"
  XGBoostFunction:
    Description: "XGBoost Lambda Function ARN"
    Value: !GetAtt XGBoostFunction.Arn
  XGBoostFunctionIamRole:
    Description: "Implicit IAM Role created for the XGBoost Lambda"
    Value: !GetAtt XGBoostFunctionRole.Arn
